groups:
  - name: prometheus-exporter-framework
    rules:
      - alert: PrometheusExporterFrameworkDown
        expr: up{job="exporter-framework"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: prometheus-exporter-framework is down
          description: Prometheus cannot scrape prometheus-exporter-framework.
