groups:
  - name: prometheus-template-exporter
    rules:
      - alert: PrometheusTemplateExporterDown
        expr: up{job="template-exporter"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: prometheus-template-exporter is down
          description: Prometheus cannot scrape prometheus-template-exporter.
