changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
    - title: CI and Maintenance
      labels:
        - ci
        - maintenance
        - github-actions
    - title: Other Changes
      labels:
        - "*"
