global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/prometheus-exporter-framework.yml

scrape_configs:
  - job_name: exporter-framework
    static_configs:
      - targets:
          - exporter:9900
